name: MayTeam
description: MayTeam
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_analytics: ^11.0.1
  firebase_messaging: ^15.0.1
  email_validator: ^2.1.17
  #rflutter_alert: ^2.0.4
  #the_validator: ^2.0.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.1.2
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.0
  go_router: ^14.2.0
  lottie: ^3.1.2
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
