name: mayteam
description: mayteam
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_messaging: ^16.0.2
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.4.2
  loading_animation_widget: ^1.2.1
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.0
  go_router: ^14.2.0
  lottie: ^3.1.2
  logger: ^2.3.0
  google_fonts: ^6.2.1
  flutter_profile_picture: ^2.0.0
  intl_phone_field: ^3.2.0
  animated_toggle_switch: ^0.8.2
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "./assets/images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/lottie/
     - assets/fonts/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900